### PR TITLE
feat(tests): add config validator + fix advanced config

### PR DESCRIPTION
**Pull request by adrienjoly**
This PR introduces a script to test the `recordExtractor` of any config.

It also fixes an error found in `config.advanced.js`, thanks to this test.

Usage information was added in `README.md`

### CODE REVIEW

**Comment by adrienjoly** [comment]
FYI, I developed that script because I intend to add a config that should be able to split the content of long web pages into more than one record, and I want to be able to simply test that config on several pages.

It would be totally ok if you think that this test script should not be added to this repo.

**Comment by bodinsamuel** [comment]
I think the repo should be as clean as possible for people that just want to check the examples. 
I would put everything you added at least in a subfolder so it can be quickly discarder by other people

**Comment by adrienjoly** [comment]
@bodinsamuel Thanks for the feedback, I agree!

That's what I ended up doing in https://github.com/algolia/crawler-configurations-examples/pull/3. (which can replace this PR, btw.)

**Comment by adrienjoly** [comment]
closing in favor to PR #3.

**Pull request closed without merging**
